#:schema node_modules/wrangler/config-schema.json
name = "secrets-bulk-do-binding-repro-do-worker"
main = "src/do-worker.ts"
compatibility_date = "2024-10-18"

[observability]
enabled = true

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]
